---
title: "625_project"
author: "weiying sun"
date: "2025-12-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# loaing 
df <- read.csv("/Users/vicky/Desktop/umich/26 fall/biostat625/project/The_Cancer_data_1500_V2.csv")
summary(df)
#View(df)
```
```{r}
colSums(is.na(df))
```
```{r}
library(tidyverse)
df <- df %>%
  mutate(
    Gender = factor(as.character(Gender), 
                    levels = c("0", "1"), 
                    labels = c("Male","Female")),
    
    Smoking = factor(as.character(Smoking), 
                     levels = c("0", "1"), 
                     labels = c("No","Yes")),
    
    CancerHistory = factor(as.character(CancerHistory), 
                           levels = c("0", "1"), 
                           labels = c("No","Yes")),
    
    GeneticRisk = factor(as.character(GeneticRisk),
                         levels = c("0","1","2"),
                         labels = c("Low","Medium","High")),
    
    Diagnosis = factor(as.character(Diagnosis),
                       levels = c("0","1"),
                       labels = c("NoCancer","Cancer"))
  )

#head(df)
```
```{r}
continuous_vars <- c("Age","BMI","PhysicalActivity","AlcoholIntake")
binary_vars <- c("Gender","Smoking","CancerHistory")
categorical_vars <- c("GeneticRisk")
target_var <- "Diagnosis"

```
```{r}
df_scaled <- df %>%
  mutate(across(all_of(continuous_vars), scale))

```
```{r}
df %>%
  pivot_longer(all_of(continuous_vars)) %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30, fill = "#6baed6", color = "black") +
  facet_wrap(~ name, scales = "free") +
  theme_minimal() +
  labs(title = "Distribution of Continuous Variables")

```
```{r}
df %>%
  pivot_longer(all_of(continuous_vars)) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot(fill = "#9ecae1") +
  theme_minimal() +
  labs(title = "Boxplots of Continuous Variables")

```
```{r}
library(corrplot)
df_corr <- df %>%
  mutate(Diagnosis_num = ifelse(Diagnosis == "Cancer", 1, 0)) %>%
  select(all_of(continuous_vars), Diagnosis_num)

corrplot(cor(df_corr), method = "color", addCoef.col = "black")

```
```{r}
df %>%
  select(all_of(c(binary_vars, categorical_vars))) %>%
  pivot_longer(everything()) %>%
  ggplot(aes(x = value)) +
  geom_bar(fill = "#fd8d3c") +
  facet_wrap(~ name, scales = "free") +
  theme_minimal() +
  labs(title = "Distribution of Binary and Categorical Variables")

```
```{r}
df %>%
  pivot_longer(continuous_vars) %>%
  ggplot(aes(x = Diagnosis, y = value, fill = Diagnosis)) +
  geom_boxplot() +
  facet_wrap(~ name, scales = "free") +
  theme_minimal() +
  labs(title = "Continuous Variables by Cancer Status")

```
```{r}
# check whether the data balance
df %>% ggplot(aes(x = Diagnosis, fill = Diagnosis)) +
  geom_bar() +
  theme_minimal() +
  labs(title = "Cancer vs Non-Cancer Distribution")
```


